// Common tech lexicon for deterministic JD keyword extraction. Each entry is a
// canonical name plus aliases; matching is case-insensitive on token
// boundaries that allow tech punctuation (C++, C#, Node.js, CI/CD).
// The user's own skills are added to this at runtime.

export interface LexiconEntry {
  term: string;
  aliases?: string[];
  /** Match case-sensitively: the term is also an everyday word or letter (Go, C, R, Express). */
  strict?: boolean;
}

export const TECH_LEXICON: LexiconEntry[] = [
  // Languages
  { term: 'JavaScript', aliases: ['JS', 'ECMAScript'] },
  { term: 'TypeScript' },
  { term: 'Python' },
  { term: 'Java' },
  { term: 'Kotlin' },
  { term: 'Go', aliases: ['Golang'], strict: true },
  { term: 'Rust' },
  { term: 'C++', aliases: ['CPP'] },
  { term: 'C#', aliases: ['CSharp'] },
  { term: 'C', strict: true },
  { term: 'Ruby' },
  { term: 'PHP' },
  { term: 'Scala' },
  { term: 'Swift', strict: true },
  { term: 'Objective-C' },
  { term: 'Dart', strict: true },
  { term: 'R', strict: true },
  { term: 'SQL' },
  { term: 'Bash', aliases: ['Shell scripting'] },
  { term: 'HTML', aliases: ['HTML5'] },
  { term: 'CSS', aliases: ['CSS3'] },
  { term: 'Solidity' },
  { term: 'Elixir' },
  { term: 'Haskell' },
  // Frontend
  { term: 'React', aliases: ['React.js', 'ReactJS'] },
  { term: 'Next.js', aliases: ['NextJS'] },
  { term: 'Vue', aliases: ['Vue.js', 'VueJS', 'Vue 3'] },
  { term: 'Angular' },
  { term: 'Svelte' },
  { term: 'Redux' },
  { term: 'Tailwind', aliases: ['Tailwind CSS', 'TailwindCSS'] },
  { term: 'React Native' },
  { term: 'Flutter' },
  { term: 'Webpack' },
  { term: 'Vite' },
  // Backend
  { term: 'Node.js', aliases: ['Node', 'NodeJS'] },
  { term: 'Express', aliases: ['Express.js', 'ExpressJS'], strict: true },
  { term: 'Fastify' },
  { term: 'NestJS' },
  { term: 'Django' },
  { term: 'Flask' },
  { term: 'FastAPI' },
  { term: 'Spring', aliases: ['Spring Boot'], strict: true },
  { term: 'Rails', aliases: ['Ruby on Rails'], strict: true },
  { term: '.NET', aliases: ['dotnet', 'ASP.NET'] },
  { term: 'GraphQL' },
  { term: 'REST', aliases: ['RESTful', 'REST APIs', 'REST API'] },
  { term: 'gRPC' },
  { term: 'WebSockets', aliases: ['WebSocket'] },
  { term: 'Microservices', aliases: ['microservice'] },
  { term: 'Kafka', aliases: ['Apache Kafka'] },
  { term: 'RabbitMQ' },
  { term: 'Celery' },
  // Data stores
  { term: 'PostgreSQL', aliases: ['Postgres'] },
  { term: 'MySQL' },
  { term: 'SQLite' },
  { term: 'MongoDB', aliases: ['Mongo'] },
  { term: 'Redis' },
  { term: 'Elasticsearch', aliases: ['OpenSearch'] },
  { term: 'Cassandra' },
  { term: 'DynamoDB' },
  { term: 'Firestore' },
  { term: 'Firebase' },
  { term: 'Snowflake' },
  { term: 'BigQuery' },
  { term: 'ClickHouse' },
  { term: 'Supabase' },
  // Cloud / infra
  { term: 'AWS', aliases: ['Amazon Web Services'] },
  { term: 'GCP', aliases: ['Google Cloud', 'Google Cloud Platform'] },
  { term: 'Azure', aliases: ['Microsoft Azure'] },
  { term: 'Docker' },
  { term: 'Kubernetes', aliases: ['K8s'] },
  { term: 'Terraform' },
  { term: 'Ansible' },
  { term: 'Linux' },
  { term: 'CI/CD', aliases: ['CI', 'continuous integration'] },
  { term: 'GitHub Actions' },
  { term: 'Jenkins' },
  { term: 'Git' },
  { term: 'Nginx' },
  { term: 'Serverless' },
  { term: 'Lambda', aliases: ['AWS Lambda'], strict: true },
  { term: 'Cloud Run' },
  { term: 'Prometheus' },
  { term: 'Grafana' },
  { term: 'Datadog' },
  { term: 'OpenTelemetry' },
  // ML / AI
  { term: 'Machine Learning', aliases: ['ML'] },
  { term: 'Deep Learning' },
  { term: 'PyTorch' },
  { term: 'TensorFlow' },
  { term: 'Keras' },
  { term: 'Scikit-learn', aliases: ['sklearn', 'scikit learn'] },
  { term: 'Pandas' },
  { term: 'NumPy' },
  { term: 'LLMs', aliases: ['LLM', 'large language models', 'large language model'] },
  { term: 'NLP', aliases: ['natural language processing'] },
  { term: 'Computer Vision' },
  { term: 'RAG', aliases: ['retrieval-augmented generation', 'retrieval augmented generation'] },
  { term: 'LangChain' },
  { term: 'LlamaIndex' },
  { term: 'Hugging Face', aliases: ['HuggingFace', 'Transformers'] },
  { term: 'OpenAI' },
  { term: 'Vertex AI' },
  { term: 'Prompt Engineering' },
  { term: 'Fine-tuning', aliases: ['fine tuning', 'finetuning'] },
  { term: 'Embeddings', aliases: ['embedding'] },
  { term: 'Vector Databases', aliases: ['vector database', 'vector DB', 'pgvector', 'Pinecone', 'Weaviate'] },
  { term: 'Agents', aliases: ['AI agents', 'agentic', 'multi-agent', 'Multi-Agent Systems'] },
  { term: 'MLOps' },
  { term: 'Spark', aliases: ['Apache Spark', 'PySpark'] },
  { term: 'Airflow', aliases: ['Apache Airflow'] },
  { term: 'dbt' },
  { term: 'ETL' },
  // Practices / concepts
  { term: 'Data Structures', aliases: ['DSA'] },
  { term: 'Algorithms' },
  { term: 'System Design' },
  { term: 'Distributed Systems' },
  { term: 'Concurrency' },
  { term: 'Unit Testing', aliases: ['unit tests', 'unit test'] },
  { term: 'Jest' },
  { term: 'Pytest' },
  { term: 'Playwright' },
  { term: 'Cypress' },
  { term: 'Agile', aliases: ['Scrum'] },
  { term: 'OOP', aliases: ['object-oriented', 'object oriented'] },
  { term: 'OAuth', aliases: ['OAuth2'] },
  { term: 'JWT' },
  { term: 'Caching' },
  { term: 'API Design' },
  { term: 'Observability' },
];
